 Thu, 09 Aug 2018 17:46:44  INFO myLogger2.py <module> [ line:22 ] hehehe
 Thu, 09 Aug 2018 17:46:46  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:46:46  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:46:46  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:46:46  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","pwd":"12345678"}
 Thu, 09 Aug 2018 17:46:46  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}
 Thu, 09 Aug 2018 17:46:46  ERROR test_api_v1.py test_register [ line:59 ] 期望结果与实际结果不匹配，用例失败！
 Thu, 09 Aug 2018 17:46:46  ERROR test_api_v1.py test_register [ line:60 ] 断言异常：
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 30, in _patched_equals
    old(self, first, second, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '{"status":1,"code":"10001","data":null,"msg":"注册成功"}' != '{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}'
- {"status":1,"code":"10001","data":null,"msg":"注册成功"}
?           ^           ---                       --
+ {"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}
?           ^         +++                       ++++++


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gemii/TestProjects/API_Framework/TestCases/test_api_v1.py", line 56, in test_register
    self.assertEqual(casedata["expected_data"],res_obj.text)  # text获取响应体
  File "/Applications/PyCharm CE.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 36, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: {"status":1,"code":"10001","data":null,"msg":"注册成功"} != {"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}
 Thu, 09 Aug 2018 17:46:49  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:46:49  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:46:49  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:46:49  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000245","pwd":"12345678","regname":"Cheese"}
 Thu, 09 Aug 2018 17:46:49  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}
 Thu, 09 Aug 2018 17:46:49  ERROR test_api_v1.py test_register [ line:59 ] 期望结果与实际结果不匹配，用例失败！
 Thu, 09 Aug 2018 17:46:49  ERROR test_api_v1.py test_register [ line:60 ] 断言异常：
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 30, in _patched_equals
    old(self, first, second, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '{"status":1,"code":"10001","data":null,"msg":"注册成功"}' != '{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}'
- {"status":1,"code":"10001","data":null,"msg":"注册成功"}
?           ^           ---                       --
+ {"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}
?           ^         +++                       ++++++


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gemii/TestProjects/API_Framework/TestCases/test_api_v1.py", line 56, in test_register
    self.assertEqual(casedata["expected_data"],res_obj.text)  # text获取响应体
  File "/Applications/PyCharm CE.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 36, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: {"status":1,"code":"10001","data":null,"msg":"注册成功"} != {"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}
 Thu, 09 Aug 2018 17:46:51  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:46:51  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:46:51  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:46:51  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"","pwd":"12345678"}
 Thu, 09 Aug 2018 17:46:52  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}
 Thu, 09 Aug 2018 17:46:52  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:46:54  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:46:54  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:46:54  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:46:54  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000247","pwd":""}
 Thu, 09 Aug 2018 17:46:54  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}
 Thu, 09 Aug 2018 17:46:54  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:46:56  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:46:56  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:46:56  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:46:56  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"1560270900","pwd":"12345678"}
 Thu, 09 Aug 2018 17:46:57  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}
 Thu, 09 Aug 2018 17:46:57  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:46:59  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:46:59  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:46:59  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:46:59  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"156027090011","pwd":"12345678"}
 Thu, 09 Aug 2018 17:46:59  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}
 Thu, 09 Aug 2018 17:46:59  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:01  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:01  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:47:01  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:47:01  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000247","pwd":"12345"}
 Thu, 09 Aug 2018 17:47:01  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20108","data":null,"msg":"密码长度必须为6~18"}
 Thu, 09 Aug 2018 17:47:01  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:04  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:04  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:47:04  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:47:04  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000247","pwd":"1234567890cheese111"}
 Thu, 09 Aug 2018 17:47:04  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20108","data":null,"msg":"密码长度必须为6~18"}
 Thu, 09 Aug 2018 17:47:04  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:07  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:07  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/register
 Thu, 09 Aug 2018 17:47:07  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：get
 Thu, 09 Aug 2018 17:47:07  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","pwd":"12345678"}
 Thu, 09 Aug 2018 17:47:07  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}
 Thu, 09 Aug 2018 17:47:07  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:09  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:09  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/login
 Thu, 09 Aug 2018 17:47:09  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:09  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","pwd":"12345678"}
 Thu, 09 Aug 2018 17:47:10  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":1,"code":"10001","data":null,"msg":"登录成功"}
 Thu, 09 Aug 2018 17:47:10  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:12  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:12  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/login
 Thu, 09 Aug 2018 17:47:12  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:12  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"","pwd":"1234567890"}
 Thu, 09 Aug 2018 17:47:12  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}
 Thu, 09 Aug 2018 17:47:12  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:14  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:14  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/login
 Thu, 09 Aug 2018 17:47:14  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:14  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","pwd":""}
 Thu, 09 Aug 2018 17:47:15  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}
 Thu, 09 Aug 2018 17:47:15  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:17  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:17  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/login
 Thu, 09 Aug 2018 17:47:17  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:17  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000247","pwd":"1234567890"}
 Thu, 09 Aug 2018 17:47:17  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}
 Thu, 09 Aug 2018 17:47:17  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:19  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:19  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/login
 Thu, 09 Aug 2018 17:47:19  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:19  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","pwd":"12345678911"}
 Thu, 09 Aug 2018 17:47:19  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}
 Thu, 09 Aug 2018 17:47:19  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:22  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:22  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:22  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:22  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","amount":"500"}
 Thu, 09 Aug 2018 17:47:22  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":1,"code":"10001","data":{"id":9818,"regname":"小蜜蜂","pwd":"25D55AD283AA400AF464C76D713C07AD","mobilephone":"15511000244","leaveamount":"1400.65","type":"1","regtime":"2018-08-09 17:19:36.0"},"msg":"充值成功"}
 Thu, 09 Aug 2018 17:47:22  ERROR test_api_v1.py test_register [ line:59 ] 期望结果与实际结果不匹配，用例失败！
 Thu, 09 Aug 2018 17:47:22  ERROR test_api_v1.py test_register [ line:60 ] 断言异常：
Traceback (most recent call last):
  File "/Users/gemii/TestProjects/API_Framework/TestCases/test_api_v1.py", line 54, in test_register
    self.assertIsNotNone(re.search(casedata["expected_data"],res_obj.text))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1239, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: unexpectedly None
 Thu, 09 Aug 2018 17:47:24  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:24  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:24  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:24  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","amount":"200.3"}
 Thu, 09 Aug 2018 17:47:24  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":1,"code":"10001","data":{"id":9818,"regname":"小蜜蜂","pwd":"25D55AD283AA400AF464C76D713C07AD","mobilephone":"15511000244","leaveamount":"1600.95","type":"1","regtime":"2018-08-09 17:19:36.0"},"msg":"充值成功"}
 Thu, 09 Aug 2018 17:47:24  ERROR test_api_v1.py test_register [ line:59 ] 期望结果与实际结果不匹配，用例失败！
 Thu, 09 Aug 2018 17:47:24  ERROR test_api_v1.py test_register [ line:60 ] 断言异常：
Traceback (most recent call last):
  File "/Users/gemii/TestProjects/API_Framework/TestCases/test_api_v1.py", line 54, in test_register
    self.assertIsNotNone(re.search(casedata["expected_data"],res_obj.text))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1239, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: unexpectedly None
 Thu, 09 Aug 2018 17:47:26  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:26  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:26  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:26  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","amount":"200.35"}
 Thu, 09 Aug 2018 17:47:26  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":1,"code":"10001","data":{"id":9818,"regname":"小蜜蜂","pwd":"25D55AD283AA400AF464C76D713C07AD","mobilephone":"15511000244","leaveamount":"1801.30","type":"1","regtime":"2018-08-09 17:19:36.0"},"msg":"充值成功"}
 Thu, 09 Aug 2018 17:47:26  ERROR test_api_v1.py test_register [ line:59 ] 期望结果与实际结果不匹配，用例失败！
 Thu, 09 Aug 2018 17:47:26  ERROR test_api_v1.py test_register [ line:60 ] 断言异常：
Traceback (most recent call last):
  File "/Users/gemii/TestProjects/API_Framework/TestCases/test_api_v1.py", line 54, in test_register
    self.assertIsNotNone(re.search(casedata["expected_data"],res_obj.text))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1239, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: unexpectedly None
 Thu, 09 Aug 2018 17:47:29  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:29  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:29  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:29  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"","amount":"200.35"}
 Thu, 09 Aug 2018 17:47:29  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}
 Thu, 09 Aug 2018 17:47:29  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:31  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:31  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:31  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:31  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","amount":"0"}
 Thu, 09 Aug 2018 17:47:31  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":1,"code":"10001","data":{"id":9818,"regname":"小蜜蜂","pwd":"25D55AD283AA400AF464C76D713C07AD","mobilephone":"15511000244","leaveamount":"1801.30","type":"1","regtime":"2018-08-09 17:19:36.0"},"msg":"充值成功"}
 Thu, 09 Aug 2018 17:47:31  ERROR test_api_v1.py test_register [ line:59 ] 期望结果与实际结果不匹配，用例失败！
 Thu, 09 Aug 2018 17:47:31  ERROR test_api_v1.py test_register [ line:60 ] 断言异常：
Traceback (most recent call last):
  File "/Users/gemii/TestProjects/API_Framework/TestCases/test_api_v1.py", line 54, in test_register
    self.assertIsNotNone(re.search(casedata["expected_data"],res_obj.text))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1239, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: unexpectedly None
 Thu, 09 Aug 2018 17:47:33  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:33  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:33  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:33  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","amount":""}
 Thu, 09 Aug 2018 17:47:33  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20115","data":null,"msg":"请输入金额"}
 Thu, 09 Aug 2018 17:47:33  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:36  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:36  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:36  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:36  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"1376024607","amount":"200"}
 Thu, 09 Aug 2018 17:47:36  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}
 Thu, 09 Aug 2018 17:47:36  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:39  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:39  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:39  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:39  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"1376024607011","amount":"200"}
 Thu, 09 Aug 2018 17:47:39  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}
 Thu, 09 Aug 2018 17:47:39  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:41  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:41  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:41  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:41  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000247","amount":"200"}
 Thu, 09 Aug 2018 17:47:41  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20104","data":null,"msg":"此手机号对应的会员不存在"}
 Thu, 09 Aug 2018 17:47:41  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:44  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:44  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:44  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:44  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","amount":"200.333"}
 Thu, 09 Aug 2018 17:47:45  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20116","data":null,"msg":"输入金额的金额小数不能超过两位"}
 Thu, 09 Aug 2018 17:47:45  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:47  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:47  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:47  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:47  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","amount":"500001"}
 Thu, 09 Aug 2018 17:47:47  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}
 Thu, 09 Aug 2018 17:47:47  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
 Thu, 09 Aug 2018 17:47:49  INFO test_api_v1.py test_register [ line:43 ] ========开始一个接口测试========
 Thu, 09 Aug 2018 17:47:49  INFO test_api_v1.py test_register [ line:44 ] 请求url为：
http://120.79.176.157:8080/futureloan/mvc/api/member/recharge
 Thu, 09 Aug 2018 17:47:49  INFO test_api_v1.py test_register [ line:45 ] 请求方法为：post
 Thu, 09 Aug 2018 17:47:49  INFO test_api_v1.py test_register [ line:46 ] 请求数据为：
{"mobilephone":"15511000244","amount":"200块"}
 Thu, 09 Aug 2018 17:47:49  INFO test_api_v1.py test_register [ line:49 ] 响应的结果为：
{"status":0,"code":"20118","data":null,"msg":"请输入数字"}
 Thu, 09 Aug 2018 17:47:49  INFO test_api_v1.py test_register [ line:57 ] 期望结果与实际结果匹配，用例成功！
